<!DOCTYPE html>
<html>
<head>
<title>Home - Ayla Gudelsky</title>
</head>
<body>
<p>HELLO WORLD</p>
</body>
    <p>At the end of the day we can endure much more than we think we can. - Frida Kahlo</p>
</html>
